name: Notify Telegram on Merge to Main/Master

on:
  push:
    branches:
      - main
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Send Telegram Notification
        run: |
          curl -X POST "https://api.telegram.org/bot8029797501:AAHvAp4KV1KUabDAFN-Kalc58MDKm1sgQyc/sendMessage" \
            -d chat_id=2052628431 \
            -d text="🚨 Merge to Main/Master Branch 🚨\nA merge has been made to the main/master branch. Please review the changes!"
